name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install \ 
              mkdocs-material \
              mkdocs-glightbox \
              mkdocs-open-in-new-tab \
              mkdocs-print-site-plugin
      - run: mkdocs gh-deploy --force

  html2pdf:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ntdesmond/html2pdf-action@v1
        with:
          path: https://cfretty.github.io/mkdocs-mat-poc/print_page/index.html
          output: ./test.pdf
          options: |
            {"format": "letter"}
      - uses: actions/upload-artifact@v3
        with:
          path: ./test.pdf
      
